// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.2
// source: profile_service.proto

package profileservicev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProfileService_UserProfileCreate_FullMethodName = "/profileservice.ProfileService/UserProfileCreate"
	ProfileService_UserProfileRead_FullMethodName   = "/profileservice.ProfileService/UserProfileRead"
	ProfileService_UserProfileUpdate_FullMethodName = "/profileservice.ProfileService/UserProfileUpdate"
	ProfileService_UserProfileDelete_FullMethodName = "/profileservice.ProfileService/UserProfileDelete"
)

// ProfileServiceClient is the client API for ProfileService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Auth is service for managing permissions and roles.
type ProfileServiceClient interface {
	// UserProfile messages
	UserProfileCreate(ctx context.Context, in *UserProfileCreateRequest, opts ...grpc.CallOption) (*UserProfileCreateResponse, error)
	UserProfileRead(ctx context.Context, in *UserProfileReadRequest, opts ...grpc.CallOption) (*UserProfileReadResponse, error)
	UserProfileUpdate(ctx context.Context, in *UserProfileUpdateRequest, opts ...grpc.CallOption) (*UserProfileUpdateResponse, error)
	UserProfileDelete(ctx context.Context, in *UserProfileDeleteRequest, opts ...grpc.CallOption) (*UserProfileDeleteResponse, error)
}

type profileServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProfileServiceClient(cc grpc.ClientConnInterface) ProfileServiceClient {
	return &profileServiceClient{cc}
}

func (c *profileServiceClient) UserProfileCreate(ctx context.Context, in *UserProfileCreateRequest, opts ...grpc.CallOption) (*UserProfileCreateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserProfileCreateResponse)
	err := c.cc.Invoke(ctx, ProfileService_UserProfileCreate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) UserProfileRead(ctx context.Context, in *UserProfileReadRequest, opts ...grpc.CallOption) (*UserProfileReadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserProfileReadResponse)
	err := c.cc.Invoke(ctx, ProfileService_UserProfileRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) UserProfileUpdate(ctx context.Context, in *UserProfileUpdateRequest, opts ...grpc.CallOption) (*UserProfileUpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserProfileUpdateResponse)
	err := c.cc.Invoke(ctx, ProfileService_UserProfileUpdate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) UserProfileDelete(ctx context.Context, in *UserProfileDeleteRequest, opts ...grpc.CallOption) (*UserProfileDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserProfileDeleteResponse)
	err := c.cc.Invoke(ctx, ProfileService_UserProfileDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProfileServiceServer is the server API for ProfileService service.
// All implementations must embed UnimplementedProfileServiceServer
// for forward compatibility.
//
// Auth is service for managing permissions and roles.
type ProfileServiceServer interface {
	// UserProfile messages
	UserProfileCreate(context.Context, *UserProfileCreateRequest) (*UserProfileCreateResponse, error)
	UserProfileRead(context.Context, *UserProfileReadRequest) (*UserProfileReadResponse, error)
	UserProfileUpdate(context.Context, *UserProfileUpdateRequest) (*UserProfileUpdateResponse, error)
	UserProfileDelete(context.Context, *UserProfileDeleteRequest) (*UserProfileDeleteResponse, error)
	mustEmbedUnimplementedProfileServiceServer()
}

// UnimplementedProfileServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProfileServiceServer struct{}

func (UnimplementedProfileServiceServer) UserProfileCreate(context.Context, *UserProfileCreateRequest) (*UserProfileCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserProfileCreate not implemented")
}
func (UnimplementedProfileServiceServer) UserProfileRead(context.Context, *UserProfileReadRequest) (*UserProfileReadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserProfileRead not implemented")
}
func (UnimplementedProfileServiceServer) UserProfileUpdate(context.Context, *UserProfileUpdateRequest) (*UserProfileUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserProfileUpdate not implemented")
}
func (UnimplementedProfileServiceServer) UserProfileDelete(context.Context, *UserProfileDeleteRequest) (*UserProfileDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UserProfileDelete not implemented")
}
func (UnimplementedProfileServiceServer) mustEmbedUnimplementedProfileServiceServer() {}
func (UnimplementedProfileServiceServer) testEmbeddedByValue()                        {}

// UnsafeProfileServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProfileServiceServer will
// result in compilation errors.
type UnsafeProfileServiceServer interface {
	mustEmbedUnimplementedProfileServiceServer()
}

func RegisterProfileServiceServer(s grpc.ServiceRegistrar, srv ProfileServiceServer) {
	// If the following call pancis, it indicates UnimplementedProfileServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProfileService_ServiceDesc, srv)
}

func _ProfileService_UserProfileCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserProfileCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).UserProfileCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProfileService_UserProfileCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).UserProfileCreate(ctx, req.(*UserProfileCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_UserProfileRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserProfileReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).UserProfileRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProfileService_UserProfileRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).UserProfileRead(ctx, req.(*UserProfileReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_UserProfileUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserProfileUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).UserProfileUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProfileService_UserProfileUpdate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).UserProfileUpdate(ctx, req.(*UserProfileUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_UserProfileDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserProfileDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).UserProfileDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProfileService_UserProfileDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).UserProfileDelete(ctx, req.(*UserProfileDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProfileService_ServiceDesc is the grpc.ServiceDesc for ProfileService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProfileService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "profileservice.ProfileService",
	HandlerType: (*ProfileServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UserProfileCreate",
			Handler:    _ProfileService_UserProfileCreate_Handler,
		},
		{
			MethodName: "UserProfileRead",
			Handler:    _ProfileService_UserProfileRead_Handler,
		},
		{
			MethodName: "UserProfileUpdate",
			Handler:    _ProfileService_UserProfileUpdate_Handler,
		},
		{
			MethodName: "UserProfileDelete",
			Handler:    _ProfileService_UserProfileDelete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "profile_service.proto",
}
