// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.2
// source: userprofile_messages.proto

package profileservicev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserProfileCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Userprofile *UserProfile `protobuf:"bytes,1,opt,name=userprofile,proto3" json:"userprofile,omitempty"`
}

func (x *UserProfileCreateRequest) Reset() {
	*x = UserProfileCreateRequest{}
	mi := &file_userprofile_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfileCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfileCreateRequest) ProtoMessage() {}

func (x *UserProfileCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userprofile_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfileCreateRequest.ProtoReflect.Descriptor instead.
func (*UserProfileCreateRequest) Descriptor() ([]byte, []int) {
	return file_userprofile_messages_proto_rawDescGZIP(), []int{0}
}

func (x *UserProfileCreateRequest) GetUserprofile() *UserProfile {
	if x != nil {
		return x.Userprofile
	}
	return nil
}

type UserProfileCreateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *UserProfileCreateResponse) Reset() {
	*x = UserProfileCreateResponse{}
	mi := &file_userprofile_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfileCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfileCreateResponse) ProtoMessage() {}

func (x *UserProfileCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userprofile_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfileCreateResponse.ProtoReflect.Descriptor instead.
func (*UserProfileCreateResponse) Descriptor() ([]byte, []int) {
	return file_userprofile_messages_proto_rawDescGZIP(), []int{1}
}

func (x *UserProfileCreateResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UserProfileReadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *UserProfileReadRequest) Reset() {
	*x = UserProfileReadRequest{}
	mi := &file_userprofile_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfileReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfileReadRequest) ProtoMessage() {}

func (x *UserProfileReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userprofile_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfileReadRequest.ProtoReflect.Descriptor instead.
func (*UserProfileReadRequest) Descriptor() ([]byte, []int) {
	return file_userprofile_messages_proto_rawDescGZIP(), []int{2}
}

func (x *UserProfileReadRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UserProfileReadResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Userprofile *UserProfile `protobuf:"bytes,1,opt,name=userprofile,proto3" json:"userprofile,omitempty"`
}

func (x *UserProfileReadResponse) Reset() {
	*x = UserProfileReadResponse{}
	mi := &file_userprofile_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfileReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfileReadResponse) ProtoMessage() {}

func (x *UserProfileReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userprofile_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfileReadResponse.ProtoReflect.Descriptor instead.
func (*UserProfileReadResponse) Descriptor() ([]byte, []int) {
	return file_userprofile_messages_proto_rawDescGZIP(), []int{3}
}

func (x *UserProfileReadResponse) GetUserprofile() *UserProfile {
	if x != nil {
		return x.Userprofile
	}
	return nil
}

type UserProfileUpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Userprofile *UserProfile `protobuf:"bytes,2,opt,name=userprofile,proto3" json:"userprofile,omitempty"`
}

func (x *UserProfileUpdateRequest) Reset() {
	*x = UserProfileUpdateRequest{}
	mi := &file_userprofile_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfileUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfileUpdateRequest) ProtoMessage() {}

func (x *UserProfileUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userprofile_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfileUpdateRequest.ProtoReflect.Descriptor instead.
func (*UserProfileUpdateRequest) Descriptor() ([]byte, []int) {
	return file_userprofile_messages_proto_rawDescGZIP(), []int{4}
}

func (x *UserProfileUpdateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserProfileUpdateRequest) GetUserprofile() *UserProfile {
	if x != nil {
		return x.Userprofile
	}
	return nil
}

type UserProfileUpdateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *UserProfileUpdateResponse) Reset() {
	*x = UserProfileUpdateResponse{}
	mi := &file_userprofile_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfileUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfileUpdateResponse) ProtoMessage() {}

func (x *UserProfileUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userprofile_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfileUpdateResponse.ProtoReflect.Descriptor instead.
func (*UserProfileUpdateResponse) Descriptor() ([]byte, []int) {
	return file_userprofile_messages_proto_rawDescGZIP(), []int{5}
}

func (x *UserProfileUpdateResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UserProfileDeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *UserProfileDeleteRequest) Reset() {
	*x = UserProfileDeleteRequest{}
	mi := &file_userprofile_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfileDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfileDeleteRequest) ProtoMessage() {}

func (x *UserProfileDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_userprofile_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfileDeleteRequest.ProtoReflect.Descriptor instead.
func (*UserProfileDeleteRequest) Descriptor() ([]byte, []int) {
	return file_userprofile_messages_proto_rawDescGZIP(), []int{6}
}

func (x *UserProfileDeleteRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UserProfileDeleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UserProfileDeleteResponse) Reset() {
	*x = UserProfileDeleteResponse{}
	mi := &file_userprofile_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfileDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfileDeleteResponse) ProtoMessage() {}

func (x *UserProfileDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_userprofile_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserProfileDeleteResponse.ProtoReflect.Descriptor instead.
func (*UserProfileDeleteResponse) Descriptor() ([]byte, []int) {
	return file_userprofile_messages_proto_rawDescGZIP(), []int{7}
}

var File_userprofile_messages_proto protoreflect.FileDescriptor

var file_userprofile_messages_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x75, 0x73, 0x65, 0x72, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x70, 0x72,
	0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x1a, 0x14, 0x70, 0x72,
	0x6f, 0x66, 0x69, 0x6c, 0x65, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x59, 0x0a, 0x18, 0x55, 0x73, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c,
	0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3d,
	0x0a, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65,
	0x52, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x22, 0x2b, 0x0a,
	0x19, 0x55, 0x73, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x28, 0x0a, 0x16, 0x55, 0x73,
	0x65, 0x72, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x58, 0x0a, 0x17, 0x55, 0x73, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x66,
	0x69, 0x6c, 0x65, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x3d, 0x0a, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c,
	0x65, 0x52, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x22, 0x69,
	0x0a, 0x18, 0x55, 0x73, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x3d, 0x0a, 0x0b, 0x75, 0x73,
	0x65, 0x72, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2e, 0x55, 0x73, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x0b, 0x75, 0x73,
	0x65, 0x72, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x22, 0x2b, 0x0a, 0x19, 0x55, 0x73, 0x65,
	0x72, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x2a, 0x0a, 0x18, 0x55, 0x73, 0x65, 0x72, 0x50, 0x72,
	0x6f, 0x66, 0x69, 0x6c, 0x65, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x22, 0x1b, 0x0a, 0x19, 0x55, 0x73, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c,
	0x65, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x28, 0x5a, 0x26, 0x61, 0x70, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x3b, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_userprofile_messages_proto_rawDescOnce sync.Once
	file_userprofile_messages_proto_rawDescData = file_userprofile_messages_proto_rawDesc
)

func file_userprofile_messages_proto_rawDescGZIP() []byte {
	file_userprofile_messages_proto_rawDescOnce.Do(func() {
		file_userprofile_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_userprofile_messages_proto_rawDescData)
	})
	return file_userprofile_messages_proto_rawDescData
}

var file_userprofile_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_userprofile_messages_proto_goTypes = []any{
	(*UserProfileCreateRequest)(nil),  // 0: profileservice.UserProfileCreateRequest
	(*UserProfileCreateResponse)(nil), // 1: profileservice.UserProfileCreateResponse
	(*UserProfileReadRequest)(nil),    // 2: profileservice.UserProfileReadRequest
	(*UserProfileReadResponse)(nil),   // 3: profileservice.UserProfileReadResponse
	(*UserProfileUpdateRequest)(nil),  // 4: profileservice.UserProfileUpdateRequest
	(*UserProfileUpdateResponse)(nil), // 5: profileservice.UserProfileUpdateResponse
	(*UserProfileDeleteRequest)(nil),  // 6: profileservice.UserProfileDeleteRequest
	(*UserProfileDeleteResponse)(nil), // 7: profileservice.UserProfileDeleteResponse
	(*UserProfile)(nil),               // 8: profileservice.UserProfile
}
var file_userprofile_messages_proto_depIdxs = []int32{
	8, // 0: profileservice.UserProfileCreateRequest.userprofile:type_name -> profileservice.UserProfile
	8, // 1: profileservice.UserProfileReadResponse.userprofile:type_name -> profileservice.UserProfile
	8, // 2: profileservice.UserProfileUpdateRequest.userprofile:type_name -> profileservice.UserProfile
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_userprofile_messages_proto_init() }
func file_userprofile_messages_proto_init() {
	if File_userprofile_messages_proto != nil {
		return
	}
	file_profile_models_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_userprofile_messages_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_userprofile_messages_proto_goTypes,
		DependencyIndexes: file_userprofile_messages_proto_depIdxs,
		MessageInfos:      file_userprofile_messages_proto_msgTypes,
	}.Build()
	File_userprofile_messages_proto = out.File
	file_userprofile_messages_proto_rawDesc = nil
	file_userprofile_messages_proto_goTypes = nil
	file_userprofile_messages_proto_depIdxs = nil
}
